<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit.Abstractions" Version="8.5.5" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="CoreLib">
      <HintPath>..\..\..\Libs\CoreLib\bin\Debug\net8.0\CoreLib.dll</HintPath>
    </Reference>
    <Reference Include="SagaContracts">
      <HintPath>..\..\..\Libs\SagaContracts\SagaContracts\bin\Debug\net8.0\SagaContracts.dll</HintPath>
    </Reference>
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
